language: node_js
node_js: node
cache:
  directories:
  - bower_components
  - node_modules
after_success: npm run build
deploy:
- provider: script
  script: htpasswd -b -n "$STAGING_USERNAME" "$STAGING_PASSWORD" > dist/.htpasswd && ./deploy-ftp.sh dist ftp.amercier.com /staging.iconsfall.com
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: rm -f dist/.htpasswd && ./deploy-ftp.sh dist ftp.amercier.com /iconsfall.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
