sudo: false
language: node_js
node_js: 4
cache:
  directories:
  - bower_components
  - node_modules
script:
- npm test
- npm run build
after_success:
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" || test "$TRAVIS_TAG" != ""
  && npm run build || echo "Not on master branch or a tag. Skipping build" >&2
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master"
  && npm run deploy-staging || echo "Not on master branch. Skipping deployment to staging" >&2
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_TAG" != ""
  && git config --global user.email "iconsfall@travis-ci.org"
  && git config --global user.name "Icon's Fall CI"
  && npm run deploy-production || echo "Not tagged. Skipping deployment to production" >&2
